
services:

  spark-master:
    image: bitnami/spark:3.5.5
    container_name: spark-master
    ports:
    - "8088:8080"
    - "7077:7077"
    environment:
    - SPARK_MODE=master
    volumes:
    - ./jobs:/opt/bitnami/spark/jobs
    networks:
      - spark-network

  spark-worker-1:
    image: bitnami/spark:3.5.5
    container_name: spark-worker-1
    environment:
    - SPARK_MODE=worker
    - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - spark-network

  # spark-worker-2:
  #   image: bitnami/spark:3.5.5
  #   container_name: spark-worker-2
  #   environment:
  #   - SPARK_MODE=worker
  #   - SPARK_MASTER_URL=spark://spark-master:7077
  #   networks:
  #     - spark-network

  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    container_name: minio
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - spark-network

  minio-mc:
    image: minio/mc:RELEASE.2025-04-08T15-39-49Z
    container_name: minio-mc
    environment:
      - MINIO_ACCESS_KEY=minioaccesskey
      - MINIO_SECRET_KEY=miniosecretkey
    entrypoint: tail -f /dev/null
    volumes:
      - ./Divvy_Trips_2019_Q4.csv:/Divvy_Trips_2019_Q4.csv
    networks:
      - spark-network
    depends_on:
      - minio

volumes:
  spark-data:
  minio-data:

networks:
  spark-network:
    driver: bridge
