
services:
  app-consumer-topic-1:
    build:
      target: app
    environment:
      TOPIC: Topic-1
    command: ["python3", "-u", "/app/consumer"]

  app-consumer-topic-2:
    build:
      target: app
    environment:
      TOPIC: Topic-2
    command: ["python3", "-u", "/app/consumer"]

  app-producer:
      build:
        target: app
      command: ["python3", "-u", "/app/producer"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
    - 32181:32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  broker-1:
    platform: linux/amd64
    image: confluentinc/cp-kafka:7.9.0
    container_name: broker-1
    ports:
      - 9091:9091
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-1:29091,EXTERNAL://localhost:9091
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
      
  # broker-2:
  #   platform: linux/amd64
  #   image: confluentinc/cp-kafka:7.9.0
  #   container_name: broker-2
  #   ports:
  #     - 9092:9092
  #   depends_on:
  #     - zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-2:29092,EXTERNAL://localhost:9092
  #     KAFKA_DEFAULT_REPLICATION_FACTOR: 2
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  #     KAFKA_NUM_PARTITIONS: 2
