
services:
  app-consumer:
    build:
      target: app
    environment:
      TOPIC: Topic-1
    # entrypoint: tail -f /dev/null
    command: ["python3", "-u", "/app/src/lab6/consumer.py"]
    develop:
      watch:
        - action: sync+restart
          path: src
          target: /app

  app-producer:
    build:
      target: app
    environment:
      TOPIC: Topic-1
    command: ["python3", "-u", "/app/src/lab6/producer.py"]

  minio:
    image: minio/minio:RELEASE.2025-04-08T15-41-24Z
    container_name: minio
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper
    hostname: zookeeper
    ports:
    - 32181:32181
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000

  broker-1:
    platform: linux/amd64
    image: confluentinc/cp-kafka:7.9.0
    container_name: broker-1
    ports:
      - 9091:9091
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-1:29091,EXTERNAL://localhost:9091
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1

